<a href="https://colab.research.google.com/github/ghnanavi09/Dav-Lab/blob/main/Program2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
df = pd.read_csv("/annex1.csv")
df.head()

,Item Code,Item Name,Category Code,Category Name
0,102900005115168,Niushou Shengcai,1011010101,Flower/Leaf Vegetables
1,102900005115199,Sichuan Red Cedar,1011010101,Flower/Leaf Vegetables
2,102900005115625,Local Xiaomao Cabbage,1011010101,Flower/Leaf Vegetables
3,102900005115748,White Caitai,1011010101,Flower/Leaf Vegetables
4,102900005115762,Amaranth,1011010101,Flower/Leaf Vegetables

In [7]:
df.tail()

,Item Code,Item Name,Category Code,Category Name
246,106958851400125,Haixian Mushroom (Bag) (4),1011010801,Edible Mushroom
247,106971533450003,Haixian Mushroom (Bunch),1011010801,Edible Mushroom
248,106971533455008,Haixian Mushroom (Bag) (3),1011010801,Edible Mushroom
249,106973223300667,Chinese Caterpillar Fungus Flowers (Box) (2),1011010801,Edible Mushroom
250,106973990980123,Hfyg Haixian Mushroom (Bunch),1011010801,Edible Mushroom

In [9]:
df.shape

(251, 4)

In [11]:
df.columns

Index(['Item Code', 'Item Name', 'Category Code', 'Category Name'], dtype='object')

In [12]:
df.describe()

          Item Code  Category Code
count  2.510000e+02   2.510000e+02
mean   1.031908e+14   1.011010e+09
std    1.048400e+12   2.915469e+02
min    1.029000e+14   1.011010e+09
25%    1.029000e+14   1.011010e+09
50%    1.029000e+14   1.011011e+09
75%    1.029000e+14   1.011011e+09
max    1.069740e+14   1.011011e+09

In [13]:
df.dropna()

,Item Code,Item Name,Category Code,Category Name
0,102900005115168,Niushou Shengcai,1011010101,Flower/Leaf Vegetables
1,102900005115199,Sichuan Red Cedar,1011010101,Flower/Leaf Vegetables
2,102900005115625,Local Xiaomao Cabbage,1011010101,Flower/Leaf Vegetables
3,102900005115748,White Caitai,1011010101,Flower/Leaf Vegetables
4,102900005115762,Amaranth,1011010101,Flower/Leaf Vegetables
...,...,...,...,...
246,106958851400125,Haixian Mushroom (Bag) (4),1011010801,Edible Mushroom
247,106971533450003,Haixian Mushroom (Bunch),1011010801,Edible Mushroom
248,106971533455008,Haixian Mushroom (Bag) (3),1011010801,Edible Mushroom
249,106973223300667,Chinese Caterpillar Fungus Flowers (Box) (2),1011010801,Edible Mushroom
250,106973990980123,Hfyg Haixian Mushroom (Bunch),1011010801,Edible Mushroom

In [14]:
df.isnull()

     Item Code  Item Name  Category Code  Category Name
0        False      False          False          False
1        False      False          False          False
2        False      False          False          False
3        False      False          False          False
4        False      False          False          False
..         ...        ...            ...            ...
246      False      False          False          False
247      False      False          False          False
248      False      False          False          False
249      False      False          False          False
250      False      False          False          False

[251 rows x 4 columns]

In [16]:
df.fillna(0)

,Item Code,Item Name,Category Code,Category Name
0,102900005115168,Niushou Shengcai,1011010101,Flower/Leaf Vegetables
1,102900005115199,Sichuan Red Cedar,1011010101,Flower/Leaf Vegetables
2,102900005115625,Local Xiaomao Cabbage,1011010101,Flower/Leaf Vegetables
3,102900005115748,White Caitai,1011010101,Flower/Leaf Vegetables
4,102900005115762,Amaranth,1011010101,Flower/Leaf Vegetables
...,...,...,...,...
246,106958851400125,Haixian Mushroom (Bag) (4),1011010801,Edible Mushroom
247,106971533450003,Haixian Mushroom (Bunch),1011010801,Edible Mushroom
248,106971533455008,Haixian Mushroom (Bag) (3),1011010801,Edible Mushroom
249,106973223300667,Chinese Caterpillar Fungus Flowers (Box) (2),1011010801,Edible Mushroom
250,106973990980123,Hfyg Haixian Mushroom (Bunch),1011010801,Edible Mushroom

In [17]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
246    False
247    False
248    False
249    False
250    False
Length: 251, dtype: bool

In [18]:
df.drop_duplicates()

,Item Code,Item Name,Category Code,Category Name
0,102900005115168,Niushou Shengcai,1011010101,Flower/Leaf Vegetables
1,102900005115199,Sichuan Red Cedar,1011010101,Flower/Leaf Vegetables
2,102900005115625,Local Xiaomao Cabbage,1011010101,Flower/Leaf Vegetables
3,102900005115748,White Caitai,1011010101,Flower/Leaf Vegetables
4,102900005115762,Amaranth,1011010101,Flower/Leaf Vegetables
...,...,...,...,...
246,106958851400125,Haixian Mushroom (Bag) (4),1011010801,Edible Mushroom
247,106971533450003,Haixian Mushroom (Bunch),1011010801,Edible Mushroom
248,106971533455008,Haixian Mushroom (Bag) (3),1011010801,Edible Mushroom
249,106973223300667,Chinese Caterpillar Fungus Flowers (Box) (2),1011010801,Edible Mushroom
250,106973990980123,Hfyg Haixian Mushroom (Bunch),1011010801,Edible Mushroom

In [19]:
df.groupby("Category Name")